# -*- coding: utf-8 -*-
"""ELECTRICITY BILL CALCULATOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12iTysOnB5JaivQQ-f3eneB4JAmzcx7IS

# **ELECTRICITY BILL CALCULATOR**
"""

print("\n ELECTRICITY BILL CALCULATOR")
print("-" * 50)

def calculate_electricity_bill():

    print("\n Welcome to the Electricity Bill Calculator!")
    print("Let me help you calculate your bill step by step.\n")

    while True:
        try:
            units = float(input("Enter the number of units consumed: "))
            if units < 0:
                print("Units cannot be negative! Please enter a valid number.")
                continue
            break
        except ValueError:
            print("Please enter a valid number!")


    total_bill = 0
    breakdown = []

    print(f"\n Calculating bill for {units} units:")
    print("-" * 40)

    # Point 1: First 50 units at Rs. 7.50/unit
    if units > 0:
        slab1_units = min(units, 50)
        slab1_cost = slab1_units * 7.50
        total_bill += slab1_cost
        breakdown.append(f"First {slab1_units} units @ Rs.7.50 = Rs.{slab1_cost:.2f}")
        print(f"First {slab1_units} units @ Rs.7.50 = Rs.{slab1_cost:.2f}")

    # Point 2: Next 50 units (51-100) at Rs. 10.75/unit
    if units > 50:
        slab2_units = min(units - 50, 50)
        slab2_cost = slab2_units * 10.75
        total_bill += slab2_cost
        breakdown.append(f"Next {slab2_units} units @ Rs.10.75 = Rs.{slab2_cost:.2f}")
        print(f"Next {slab2_units} units @ Rs.10.75 = Rs.{slab2_cost:.2f}")

    # Point 3: Next 100 units (101-200) at Rs. 15.20/unit
    if units > 100:
        slab3_units = min(units - 100, 100)
        slab3_cost = slab3_units * 15.20
        total_bill += slab3_cost
        breakdown.append(f"Next {slab3_units} units @ Rs.15.20 = Rs.{slab3_cost:.2f}")
        print(f"Next {slab3_units} units @ Rs.15.20 = Rs.{slab3_cost:.2f}")

    # Point 4: Above 200 units at Rs. 20.50/unit
    if units > 200:
        slab4_units = units - 200
        slab4_cost = slab4_units * 20.50
        total_bill += slab4_cost
        breakdown.append(f"Remaining {slab4_units} units @ Rs.20.50 = Rs.{slab4_cost:.2f}")
        print(f"Remaining {slab4_units} units @ Rs.20.50 = Rs.{slab4_cost:.2f}")

    print(f"\nBase bill amount: Rs.{total_bill:.2f}")

    # Add surcharge (20%)
    surcharge = total_bill * 0.20
    print(f"Surcharge (20%): Rs.{surcharge:.2f}")

    # fuel adjustment (10% on total after surcharge)
    bill_after_surcharge = total_bill + surcharge
    fuel_adjustment = bill_after_surcharge * 0.10
    print(f"Fuel Adjustment (10%): Rs.{fuel_adjustment:.2f}")

    # Final bill calculation
    final_bill = bill_after_surcharge + fuel_adjustment

    print("\n" + "=" * 40)
    print(f" FINAL ELECTRICITY BILL: Rs.{final_bill:.2f}")
    print("=" * 40)

    return final_bill

calculate_electricity_bill()

print("\n\n")